export const GET_PIZZA = 'GET_PIZZA';
export const GET_PIZZA_SUCCESS = 'GET_PIZZA_SUCCESS';
export const GET_PIZZA_LOADING = 'GET_PIZZA_LOADING';
export const GET_PIZZA_FAILURE = 'GET_PIZZA_FAILURE';

export const SORT_BY = 'SORT_BY';
export const SORT_BY_SUCCESS = 'SORT_BY_SUCCESS';
export const SORT_BY_FAILURE = 'SORT_BY_FAILURE';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const FILTER_CATEGORY_SUCCESS = 'FILTER_CATEGORY_SUCCESS';
export const FILTER_CATEGORY_FAILURE = 'FILTER_CATEGORY_FAILURE';

export const ADD_PIZZA_TO_CART = 'ADD_PIZZA_TO_CART';
export const ADD_PIZZA_TO_CART_SUCCESS = 'ADD_PIZZA_TO_CART_SUCCESS';
export const ADD_PIZZA_TO_CART_FAILURE = 'ADD_PIZZA_TO_CART_FAILURE';

export const UPDATE_PIZZA_CART_ITEM_ = 'UPDATE_PIZZA_CART_ITEM';
export const UPDATE_PIZZA_CART_ITEM_SUCCESS = 'UPDATE_PIZZA_CART_ITEM_SUCCESS';

export const INC_PIZZA_AMOUNT = 'INC_PIZZA_AMOUNT';
export const INC_PIZZA_AMOUNT_SUCCESS = 'INC_PIZZA_AMOUNT_SUCCESS';
export const INC_PIZZA_AMOUNT_FAILURE = 'INC_PIZZA_AMOUNT_FAILURE';

export const DEC_PIZZA_AMOUNT = 'DEC_PIZZA_AMOUNT';
export const DEC_PIZZA_AMOUNT_SUCCESS = 'DEC_PIZZA_AMOUNT_SUCCESS';
export const DEC_PIZZA_AMOUNT_FAILURE = 'DEC_PIZZA_AMOUNT_FAILURE';

export const DELETE_PIZZA_ITEM = 'DELETE_PIZZA_ITEM';
export const DELETE_PIZZA_ITEM_SUCCESS = 'DELETE_PIZZA_ITEM_SUCCESS';
export const DELETE_PIZZA_ITEM_FAILURE = 'DELETE_PIZZA_ITEM_FAILURE';

export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAILURE = 'CLEAR_CART_FAILURE';
